"""
agents/query_crew.py
--------------------
Assembles the Query Crew:
  Architect → Generator → Reviewer (sequential)

Also provides an auto-correction loop:
  If the Reviewer rejects, it re-tasks the Generator (max 2 retries).
"""

from __future__ import annotations

import logging
import re
from typing import Optional

from crewai import Crew, Task, Process

from app.agents.architect import build_architect
from app.agents.generator import build_generator
from app.agents.reviewer import build_reviewer
from app.models.query_plan import ExecutionPlan, ValidatedQueryPlan

logger = logging.getLogger(__name__)

MAX_CORRECTION_ATTEMPTS = 2


def _extract_sql(raw_output: str) -> str:
    """Pull the first SQL block from crew output."""
    # Try fenced block first
    m = re.search(r"```(?:sql)?\s*(.*?)```", raw_output, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip()
    # Fallback: look for SELECT/INSERT/UPDATE/DELETE
    m = re.search(r"(SELECT|INSERT|UPDATE|DELETE|WITH)\b.*", raw_output, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(0).strip()
    return raw_output.strip()


def run_query_crew(
    question: str,
    dialect: str,
    session_history: str = "",
    step_callback=None,
) -> ValidatedQueryPlan:
    """
    Run the full Architect → Generator → Reviewer pipeline.
    Returns a ValidatedQueryPlan.
    On Reviewer rejection, automatically retries the Generator (max 2x).
    """
    architect = build_architect()
    generator = build_generator()
    reviewer = build_reviewer()

    plan_task = Task(
        description=f"""Analyze the user's request and produce an execution plan.

User request: {question}
SQL dialect: {dialect}
Conversation history: {session_history or "None"}

Use the fetch_schema_context tool to retrieve relevant table DDLs before planning.
Output a structured plan with: steps (list), tables_involved (list), requires_transaction (bool), risk_level (str).""",
        expected_output="A JSON-compatible execution plan with steps, tables_involved, requires_transaction, and risk_level fields.",
        agent=architect,
    )

    gen_task = Task(
        description=f"""Based on the Architect's plan, generate the SQL query.

Dialect: {dialect}
User request: {question}

Use the fetch_schema_context tool to verify all column and table names.
Use the fetch_query_history tool for few-shot examples.
Return ONLY the final SQL statement — no explanation, no markdown.""",
        expected_output="A single valid SQL statement, no markdown fences.",
        agent=generator,
        context=[plan_task],
    )

    review_task = Task(
        description="""Review the SQL generated by the Generator.
Use the validate_sql_ast tool to check safety.
Return exactly 'APPROVED' or 'REJECTED: <reason>'.""",
        expected_output="APPROVED or REJECTED: <reason>",
        agent=reviewer,
        context=[gen_task],
    )

    crew = Crew(
        agents=[architect, generator, reviewer],
        tasks=[plan_task, gen_task, review_task],
        process=Process.sequential,
        verbose=True,
        step_callback=step_callback,
    )

    result = crew.kickoff()
    review_output = str(result.raw).strip()

    # Check for rejection → trigger correction loop
    correction_attempt = 0
    while review_output.upper().startswith("REJECTED") and correction_attempt < MAX_CORRECTION_ATTEMPTS:
        rejection_reason = review_output[len("REJECTED:"):].strip() if ":" in review_output else review_output
        logger.warning("Reviewer rejected SQL (attempt %d): %s", correction_attempt + 1, rejection_reason)
        correction_attempt += 1

        # Re-task the generator with the rejection reason
        correction_gen = Task(
            description=f"""The SQL you generated was rejected by the Safety Reviewer.

Rejection reason: {rejection_reason}
Original request: {question}
Dialect: {dialect}

Fix the SQL to address the rejection reason. Return ONLY the corrected SQL.""",
            expected_output="A corrected SQL statement with no markdown fences.",
            agent=generator,
        )
        correction_review = Task(
            description="""Review the corrected SQL.
Use the validate_sql_ast tool.
Return exactly 'APPROVED' or 'REJECTED: <reason>'.""",
            expected_output="APPROVED or REJECTED: <reason>",
            agent=reviewer,
            context=[correction_gen],
        )
        correction_crew = Crew(
            agents=[generator, reviewer],
            tasks=[correction_gen, correction_review],
            process=Process.sequential,
            verbose=True,
            step_callback=step_callback,
        )
        result = correction_crew.kickoff()
        review_output = str(result.raw).strip()

    approved = not review_output.upper().startswith("REJECTED")
    rejection_reason: Optional[str] = None
    if not approved:
        rejection_reason = review_output[len("REJECTED:"):].strip() if ":" in review_output else review_output

    # Extract SQL from generator task result
    gen_result = gen_task.output.raw if gen_task.output else ""
    sql = _extract_sql(gen_result)

    return ValidatedQueryPlan(
        sql=sql,
        dialect=dialect,
        is_destructive=any(kw in sql.upper() for kw in ("DROP", "TRUNCATE", "DELETE")),
        approved=approved,
        rejection_reason=rejection_reason,
    )
